name: MSurvivalCompass
version: 9.0-github-design
main: pl.msurvival.compass.MSurvivalCompass
api-version: '1.21'
author: Milekz
softdepend:
  - MSurvivalKeys
  - MSurvivalMarket
  - Multiverse-Core
commands:
  mscompass:
    usage: /mscompass reload
    aliases: [compassreload]
  lobby:
    usage: /lobby
  survival:
    usage: /survival
  setmsspawn:
    usage: /setmsspawn <lobby|survival>
permissions:
  msurvival.compass.admin:
    default: op
  msurvival.compass.use:
    default: true
